### ISSUE TITLE
The voice indicator shows always active

### ISSUE THREAD

**Issue by Luois45** [MiniDiscordThemes/Squared#2]
When being in a voice channel or private call it shows always green as it would be sending voice data.
![image](https://github.com/MiniDiscordThemes/Squared/assets/58306774/2a12dbbc-c0b7-42f1-ba58-e0109328c50e)

**Comment by Saltssaumure** [comment]
This is most likely a RadialStatus issue: https://github.com/DiscordStyles/RadialStatus/issues
