### ISSUE TITLE
user profile icons in main chat area are circular

### ISSUE THREAD

**Issue by robotimdevloper** [MiniDiscordThemes/Squared#4]
as stated in the title user profile icons in the main chatting area are still circular while they are sqaure everywhere else, i am using the vencord version

**Comment by Saltssaumure** [comment]
Discord has been continuously making changes to the classes, currently waiting for changes to settle before making updates.

**Comment by Saltssaumure** [comment]
This issue seems to have self-resolved, please re-open if the issue still (re)-occurs.
